### ISSUE TITLE
Upgrade six to 1.8.0

### ISSUE THREAD

**Issue by Almad** [paver/paver#139]
Since 1.7, tests are failing with "Cannot import _winreg" on debian jessie.

**Comment by adiroiban** [comment]
I have updated to paver 1.2.4 and this was fixed...

six is now at 1.9.0

**Comment by Arfrever** [comment]
Paver has its own copy of `six` located at `paver/deps/six.py`, which currently has version `1.6.1`.
Before upgrading it, issue #147 should be fixed.

**Comment by kxepal** [comment]
Any progress here or a serious reason to ship own six instead of using package dependencies? Because currently paver causes quite awkward issues (impyla says hi):
```>>> from six.moves import range
>>> range
<type 'xrange'>
>>> import paver.tasks
>>> from six.moves import range
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name range
```

**Comment by Almad** [comment]
Good point, let's change it in 1.3 (with #162 )

**Comment by NfNitLoop** [comment]
I'm getting errors regarding importing winreg on Python 3.5 on OSX (via Homebrew).  I assume it's related to this issue? 

~~~
Captured Task Output:
---------------------

---> paver.tasks.help
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/paver/tasks.py", line 196, in _run_task
    return do_task()
  File "/usr/local/lib/python3.5/site-packages/paver/tasks.py", line 193, in do_task
    return func(**kw)
  File "/usr/local/lib/python3.5/site-packages/paver/tasks.py", line 781, in help
    task_list = environment.get_tasks()
  File "/usr/local/lib/python3.5/site-packages/paver/tasks.py", line 229, in get_tasks
    scan_module(self.pavement)
  File "/usr/local/lib/python3.5/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/usr/local/lib/python3.5/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/usr/local/lib/python3.5/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/usr/local/lib/python3.5/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/usr/local/lib/python3.5/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/usr/local/lib/python3.5/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/usr/local/lib/python3.5/site-packages/paver/tasks.py", line 224, in scan_module
    item = getattr(module, name, None)
  File "/usr/local/lib/python3.5/site-packages/botocore/vendored/six.py", line 89, in __get__
    result = self._resolve()
  File "/usr/local/lib/python3.5/site-packages/botocore/vendored/six.py", line 108, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python3.5/site-packages/botocore/vendored/six.py", line 79, in _import_module
    __import__(name)
ImportError: No module named 'winreg'
~~~

~~~
$ pip3 freeze |grep -iE 'paver|six'
Paver==1.2.4
six==1.10.0
~~~

**Comment by Almad** [comment]
Also, I found tests failing on 3.5, and I'll probably fix that by bumping major version and dropping <2.7 now that jython 2.7 is out.

Also see #162

**Comment by hugovk** [comment]
See PR https://github.com/paver/paver/pull/180 to devendor six.

**Comment by Almad** [comment]
Six is now devendored.
