### ISSUE TITLE
Paver incompatible with six >=1.7.0

### ISSUE THREAD

**Issue by Arfrever** [paver/paver#147]
six >=1.7.0 contains some changes, which cause that trying to use attributes of unavailable module results in ImportError.

Example:
Test suite of Paver and Python 2.7 with deleted `/usr/lib64/python2.7/lib-dynload/gdbm.so`:
```
$ nosetests-2.7
...................................................E..EE.........................................
======================================================================
ERROR: paver.tests.test_tasks.test_list_tasks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/paver/paver/tests/test_tasks.py", line 162, in test_list_tasks
    task_list = tasks.environment.get_tasks()
  File "/tmp/paver/paver/tasks.py", line 229, in get_tasks
    scan_module(self.pavement)
  File "/tmp/paver/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/tmp/paver/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/tmp/paver/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/tmp/paver/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/tmp/paver/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/tmp/paver/paver/tasks.py", line 224, in scan_module
    item = getattr(module, name, None)
  File "/tmp/paver/paver/deps/six.py", line 90, in __get__
    result = self._resolve()
  File "/tmp/paver/paver/deps/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/tmp/paver/paver/deps/six.py", line 80, in _import_module
    __import__(name)
ImportError: No module named gdbm

======================================================================
ERROR: paver.tests.test_tasks.test_shortname_access
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/paver/paver/tests/test_tasks.py", line 195, in test_shortname_access
    task = environment.get_task("help")
  File "/tmp/paver/paver/tasks.py", line 131, in get_task
    all_tasks = self.get_tasks()
  File "/tmp/paver/paver/tasks.py", line 229, in get_tasks
    scan_module(self.pavement)
  File "/tmp/paver/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/tmp/paver/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/tmp/paver/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/tmp/paver/paver/tasks.py", line 224, in scan_module
    item = getattr(module, name, None)
  File "/tmp/paver/paver/deps/six.py", line 90, in __get__
    result = self._resolve()
  File "/tmp/paver/paver/deps/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/tmp/paver/paver/deps/six.py", line 80, in _import_module
    __import__(name)
ImportError: No module named gdbm

======================================================================
ERROR: paver.tests.test_tasks.test_longname_access
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/paver/paver/tests/test_tasks.py", line 204, in test_longname_access
    task = environment.get_task("nosuchmodule.nosuchtask")
  File "/tmp/paver/paver/tasks.py", line 131, in get_task
    all_tasks = self.get_tasks()
  File "/tmp/paver/paver/tasks.py", line 229, in get_tasks
    scan_module(self.pavement)
  File "/tmp/paver/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/tmp/paver/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/tmp/paver/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/tmp/paver/paver/tasks.py", line 224, in scan_module
    item = getattr(module, name, None)
  File "/tmp/paver/paver/deps/six.py", line 90, in __get__
    result = self._resolve()
  File "/tmp/paver/paver/deps/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/tmp/paver/paver/deps/six.py", line 80, in _import_module
    __import__(name)
ImportError: No module named gdbm

----------------------------------------------------------------------
Ran 97 tests in 0.373s

FAILED (errors=3)
```

Problem was originally found when testing with Jython, which has no `gdbm` module.

Fix:
```
--- paver/tasks.py
+++ paver/tasks.py
@@ -221,7 +221,10 @@
         def scan_module(module):
             modules.add(module)
             for name in dir(module):
-                item = getattr(module, name, None)
+                try:
+                    item = getattr(module, name, None)
+                except ImportError:
+                    item = None
                 if isinstance(item, Task):
                     result.add(item)
                 if isinstance(item, types.ModuleType) and item not in modules:
```

**Comment by Almad** [comment]
Thanks!
