### ISSUE TITLE
pkg_resources embedded six breaks in paver (gdbm).. scan_modules needs better recovery

### ISSUE THREAD

**Issue by kkvilekval** [paver/paver#165]
Using the latest pip and setuptools 

```
$ mkvirtualenv  pavertest
New python executable in pavertest/bin/python
Please make sure you remove any previous custom paths from your /home/kgk/.pydistutils.cfg file.
Installing setuptools, pip...done.
(pavertest)$ pip install -U pip setuptools
Downloading/unpacking pip from https://biodev.ece.ucsb.edu/py/root/pypi/+f/057/0520434c5b600/pip-8.1.2-py2.py3-none-any.whl#md5=0570520434c5b600d89ec95393b2650b
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB): 1.2MB downloaded
Downloading/unpacking setuptools from https://biodev.ece.ucsb.edu/py/root/pypi/+f/500/111194524d298/setuptools-21.2.1-py2.py3-none-any.whl#md5=500111194524d298be920518ff2200a4
  Downloading setuptools-21.2.1-py2.py3-none-any.whl (509kB): 509kB downloaded
Installing collected packages: pip, setuptools
  Found existing installation: pip 1.5.4
    Uninstalling pip:
      Successfully uninstalled pip
  Found existing installation: setuptools 2.2
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed pip setuptools
Cleaning up...
```

Using the latest paver

```
(pavertest)$ pip install paver
Collecting paver
  Downloading https://biodev.ece.ucsb.edu/py/root/pypi/+f/329/879febfa24303/Paver-1.2.4-py2.py3-none-any.whl (295kB)
    100% |████████████████████████████████| 296kB 30.3MB/s 
Installing collected packages: paver
Successfully installed paver-1.2.4

```

```
$ paver 
(pavertest)$ paver 
Traceback (most recent call last):
  File "/home/kgk/Envs/pavertest/bin/paver", line 11, in <module>
    sys.exit(main())
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/paver/tasks.py", line 878, in main
    _launch_pavement(args)
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/paver/tasks.py", line 858, in _launch_pavement
    _process_commands(args, auto_pending=auto_pending)
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/paver/tasks.py", line 804, in _process_commands
    task = environment.get_task('default')
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/paver/tasks.py", line 131, in get_task
    all_tasks = self.get_tasks()
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/paver/tasks.py", line 229, in get_tasks
    scan_module(self.pavement)
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/paver/tasks.py", line 224, in scan_module
    item = getattr(module, name, None)
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/pkg_resources/_vendor/six.py", line 92, in __get__
    result = self._resolve()
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/pkg_resources/_vendor/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/kgk/Envs/pavertest/local/lib/python2.7/site-packages/pkg_resources/_vendor/six.py", line 82, in _import_module
    __import__(name)
ImportError: No module named gdbm

```

I can resolve this installing at the system level python-gdbm.. BUT we are in isolated virtualenv..

```
$ sudo  apt-get install python-gdbm
...
(pavertest)$ paver
(pavertest)$ 

```

Should there be a try-except somewhere to stop these errors?

**Comment by Almad** [comment]
Hmm, related: #139 and vendoring in #162

**Comment by Almad** [comment]
@kkvilekval Could you please provide info about what system and version are you on?

Can't reproduce on mine, and there _is_ a try/except for `ImportError` in place, so I'd love to dig deeper.

**Comment by kkvilekval** [comment]
The system was a recent debian jessie with standard python install and virtualenvwrapper

**Comment by Almad** [comment]
@kkvilekval I unfortunately still can't reproduce. Could you please help me with reproduction steps?

This is what I am doing?

```
almad@zeruel:~/projects/paver$ cat Dockerfile.165 
FROM debian:jessie

RUN apt-get update && \
        apt-get -y upgrade && \
        apt-get -y install virtualenvwrapper

RUN useradd -ms /bin/bash paver

USER paver
WORKDIR /home/paver

RUN echo 'source "/usr/bin/virtualenvwrapper.sh"' >> ~/.bash_profile && \
        echo 'export WORKON_HOME="/home/paver/virtualenvs/"' >> ~/.bash_profile

almad@zeruel:~/projects/paver$ docker build -t paver-165 -f Dockerfile.165 .
(...)
almad@zeruel:~/projects/paver$ docker run -it paver-165 
paver@27129f3b1532:~$ mkvirtualenv  pavertest
Running virtualenv with interpreter /usr/bin/python2
New python executable in pavertest/bin/python2
Also creating executable in pavertest/bin/python
Installing setuptools, pip...done.
(pavertest)paver@27129f3b1532:~$ pip install -U pip setuptools
Downloading/unpacking pip from https://pypi.python.org/packages/9c/32/004ce0852e0a127f07f358b715015763273799bd798956fa930814b60f39/pip-8.1.2-py2.py3-none-any.whl#md5=0570520434c5b600d89ec95393b2650b
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB): 1.2MB downloaded
Downloading/unpacking setuptools from https://pypi.python.org/packages/74/7c/c75c4f4032a4627406db06b742cdc7ba24c4833cd423ea7e22882380abde/setuptools-23.0.0-py2.py3-none-any.whl#md5=a066fd7bfb8faaad763acbdbcb290199
  Downloading setuptools-23.0.0-py2.py3-none-any.whl (435kB): 435kB downloaded
Installing collected packages: pip, setuptools
  Found existing installation: pip 1.5.6
    Uninstalling pip:
      Successfully uninstalled pip
  Found existing installation: setuptools 5.5.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed pip setuptools
Cleaning up...
(pavertest)paver@27129f3b1532:~$ pip install paver
Collecting paver
  Downloading Paver-1.2.4-py2.py3-none-any.whl (295kB)
    100% |################################| 296kB 1.0MB/s 
Installing collected packages: paver
Successfully installed paver-1.2.4
(pavertest)paver@27129f3b1532:~$ paver
(pavertest)paver@27129f3b1532:~$ paver help
---> paver.tasks.help
Usage: paver [global options] taskname [task options] [taskname [taskoptions]]

Options:
  --version             show program's version number and exit
  -n, --dry-run         don't actually do anything
  -v, --verbose         display all logging output
  -q, --quiet           display only errors
  -i, --interactive     enable prompting
  -f FILE, --file=FILE  read tasks from FILE [pavement.py]
  -h, --help            display this help information
  --propagate-traceback
                        propagate traceback, do not hide it under
                        BuildFailure(for debugging)
  -x COMMAND_PACKAGES, --command-packages=COMMAND_PACKAGES
                        list of packages that provide distutils commands

Tasks from paver.misctasks:
  generate_setup - Generates a setup.py file that uses paver behind the scenes
  minilib        - Create a Paver mini library that contains enough for a simple
    pavement.py to be installed using a generated setup.py
  paverdocs      - Open your web browser and display Paver's documentation.

Tasks from paver.tasks:
  help           - This help display.
(pavertest)paver@27129f3b1532:~$ 

```

**Comment by Almad** [comment]
@kkvilekval This is in your output and looks suspicious: `Please make sure you remove any previous custom paths from your /home/kgk/.pydistutils.cfg file.`

Anything in there / would removal help?

**Comment by mpatibandla** [comment]
I got the exact same traceback. Is this resolved? @kkvilekval  @Almad

**Comment by Almad** [comment]
@mpatibandla I can't reproduce—are you willing to help?

Do you use wrapper as well, virtualenv or pure python install?

Are you using Jessie as well, or something else?

**Comment by hoangelos** [comment]
So I can reproduce this at will.  Whenever, you have a. paver file that import boto3 or botocore, then this is when the error occurs.  It fails when trying to find the tasks, so if you do paver help or call paver without any args.

**Comment by hoangelos** [comment]
Actually my error is close, but not the same...

HallidayBookPro:terrestrial-pipeline-lambdas halliday$ paver
Traceback (most recent call last):
  File "/Users/halliday/.pyenv/versions/3.4.3/bin/paver", line 11, in <module>
    sys.exit(main())
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/paver/tasks.py", line 878, in main
    _launch_pavement(args)
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/paver/tasks.py", line 858, in _launch_pavement
    _process_commands(args, auto_pending=auto_pending)
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/paver/tasks.py", line 804, in _process_commands
    task = environment.get_task('default')
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/paver/tasks.py", line 131, in get_task
    all_tasks = self.get_tasks()
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/paver/tasks.py", line 229, in get_tasks
    scan_module(self.pavement)
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/paver/tasks.py", line 224, in scan_module
    item = getattr(module, name, None)
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/botocore/vendored/six.py", line 92, in __get__
    result = self._resolve()
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/botocore/vendored/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/site-packages/botocore/vendored/six.py", line 82, in _import_module
    __import__(name)
  File "/Users/halliday/.pyenv/versions/3.4.3/lib/python3.4/dbm/gnu.py", line 3, in <module>
    from _gdbm import *
ImportError: No module named '_gdbm'

**Comment by Almad** [comment]
Looking at stacktrace, it actually may be because botocore is vendoring six, as well as Paver. Will take a look / think about it, those vendored deps get hairy very quickly :S

**Comment by hoangelos** [comment]
This is really a part of an off topic suggestion that intersects both ideas.  While scanning the modules to find tasks, what if you ignored any import errors.  Skipping the broken code.

**Comment by Almad** [comment]
Latest release unvendored six. Could you please confirm this helped with this issue?
