### ISSUE TITLE
Unspecified options raise AttributeError instead of being `None`

### ISSUE THREAD

**Issue by winni-genp** [paver/paver#173]
When I run `paver test` on this `pavement.py` file:
```python
# pavement.py
from paver.easy import *


@task
@cmdopts([('verbose', 'v', 'Turn on debugging info')])
def test():
    print(options.verbose)
```

I get the output
```
---> pavement.test


Captured Task Output:
---------------------

---> pavement.test
Traceback (most recent call last):
  File "/local/scratch/winni/proj/EchiDNA/mandela/miniconda/lib/python2.7/site-packages/paver/tasks.py", line 196, in _run_task
    return do_task()
  File "/local/scratch/winni/proj/EchiDNA/mandela/miniconda/lib/python2.7/site-packages/paver/tasks.py", line 193, in do_task
    return func(**kw)
  File "pavement.py", line 8, in test
    print(options.verbose)
  File "/local/scratch/winni/proj/EchiDNA/mandela/miniconda/lib/python2.7/site-packages/paver/easy.py", line 42, in __getattr__
    return getattr(self.__get_object(), attr)
  File "/local/scratch/winni/proj/EchiDNA/mandela/miniconda/lib/python2.7/site-packages/paver/options.py", line 23, in __getattr__
    raise AttributeError(name)
AttributeError: verbose
```

As a consequence I find myself writing this code in order to set missing flags to `None`:
```python
if not hasattr(options, 'verbose'):
    options.verbose = None
```

This seems unnecessary.  Is this expected behavior and am I missing a better way of doing this?  

Also, Is there a good way to specify default values for command line arguments?

**Comment by Almad** [comment]
This is unfortunately the way `optparse` works, although I'd suggest this oneliner:

`verbose = getattr(options, 'verbose', None)`

As for default values, you can do this:

```
    from optparse import make_option

    @tasks.task
    @tasks.cmdopts([
        make_option("-f", "--foo", help="foo", default="baz")
    ])
    def t1(options):
        assert options.foo == "baz"
```

**Comment by winni-genp** [comment]
Ah, perfect!  Thanks for the help.

I saw the `make_option` usage on the documentation page at https://pythonhosted.org/Paver/pavement.html?highlight=make_option, but I could not get it to work because `from optparse import make_option` is missing in the example of the documentation.  I suggest an update to the documentation page to this effect.

**Comment by Almad** [comment]
Good point—will close the issue once I do.
