### ISSUE TITLE
paver crash if open UTF-8 file on Windows 7

### ISSUE THREAD

**Issue by foobarjohnny** [paver/paver#182]
[Error description]
run the UTF-8 pavement.py inside zip file under Python 3.6 on Windows 7, it will cause crash as below :

Traceback (most recent call last):
  File "d:\program files\python\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python\Python3\Scripts\paver.exe\__main__.py", line 9, in <module>
  File "d:\program files\python\python3\lib\site-packages\paver\tasks.py", line 891, in main
    _launch_pavement(args)
  File "d:\program files\python\python3\lib\site-packages\paver\tasks.py", line 856, in _launch_pavement
    source = pf.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 54: illegal multibyte sequence

[Reason]
On Windows 7, the default encoding of open() is not UTF-8 but the system's code page setting.

[Resolution]
Before
         pf = open(environment.pavement_file)
It should detect the file encoding of <environment.pavement_file>, then use
         pf = open(environment.pavement_file, encoding='<the_correct_encoding>')
to open the file.

[pavement.zip](https://github.com/paver/paver/files/1446334/pavement.zip)

**Comment by Almad** [comment]
Thanks for the report! Looks like an easy fix, I'll just try to add a test as well

**Comment by dogatana** [comment]
Hi, how this is going?

I just start using paver in my environment, Python 3.7 on Windows10, and faces this issue.
Python 3.* uses UTF-8 as the default source code encoding,  so UTF-8 seems good.

As a counter measure, I put the magic comment on the top of the pavement.py.
But I'm looking forward for the update.

Thank you in advance!

**Comment by Almad** [comment]
Hi, this fell off my radar a bit, mostly as I’ve been looking into pruning the repo to drop py2 support. Good poke, lemme find some time to work on the next release. Of course, PR welcome if interested :)

**Comment by dogatana** [comment]
I've replace paver in my environment with

```
pip install git+https://github.com/paver/paver.git
```

Now it works fine with Python3 default source encoding, thanks !
