### ISSUE TITLE
Paver breaks "six" with Python 3.6

### ISSUE THREAD

**Issue by mejedi** [paver/paver#183]
The following snippet breaks under Python 3.6, probably related to #139.

``` Python
# runner.py
from paver.tasks import main
main()
```
``` Python
# pavement.py
import six
```
Running:
```
$ python runner.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 37, in <module>
    import _tkinter
ModuleNotFoundError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner.py", line 2, in <module>
    main()
  File "/home/nickz/xxx/lib/python3.6/site-packages/paver/tasks.py", line 878, in main
    _launch_pavement(args)
  File "/home/nickz/xxx/lib/python3.6/site-packages/paver/tasks.py", line 858, in _launch_pavement
    _process_commands(args, auto_pending=auto_pending)
  File "/home/nickz/xxx/lib/python3.6/site-packages/paver/tasks.py", line 804, in _process_commands
    task = environment.get_task('default')
  File "/home/nickz/xxx/lib/python3.6/site-packages/paver/tasks.py", line 131, in get_task
    all_tasks = self.get_tasks()
  File "/home/nickz/xxx/lib/python3.6/site-packages/paver/tasks.py", line 229, in get_tasks
    scan_module(self.pavement)
  File "/home/nickz/xxx/lib/python3.6/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/home/nickz/xxx/lib/python3.6/site-packages/paver/tasks.py", line 228, in scan_module
    scan_module(item)
  File "/home/nickz/xxx/lib/python3.6/site-packages/paver/tasks.py", line 224, in scan_module
    item = getattr(module, name, None)
  File "/home/nickz/xxx/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/home/nickz/xxx/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/nickz/xxx/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 39, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
```

Packages in use:
```
$ pip freeze
Paver==1.2.4
pkg-resources==0.0.0
six==1.11.0
```

**Comment by Almad** [comment]
@mejedi Would it please be possible for you to retest with the latest master?

**Comment by mejedi** [comment]
Yay, it works! Hoping to get a release soon :)

**Comment by Almad** [comment]
@mejedi Sounds good! Let me just retest few more cases with six and get autorelease working and move it out, hope to get it next week

**Comment by mejedi** [comment]
bump

**Comment by Almad** [comment]
@mejedi Released. Does it work for you on the release version, please?
