### ISSUE TITLE
Doesn't work with virtualenv 20

### ISSUE THREAD

**Issue by felixonmars** [paver/paver#205]
```
======================================================================
ERROR: test_minilib_bundles_extra_files (tests_integration.test_minilib.TestMinilib)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 30, in setUp
    self.prepare_virtualenv()
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 37, in prepare_virtualenv
    self.bootstrap_virtualenv()
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 57, in bootstrap_virtualenv
    paver.virtual._create_bootstrap(script_name="bootstrap.py",
  File "/build/python-paver/src/paver-Paver-1.3.4/paver/virtual.py", line 91, in _create_bootstrap
    bootstrap_contents = venv.create_bootstrap_script(extra_text)
AttributeError: module 'virtualenv' has no attribute 'create_bootstrap_script'

======================================================================
ERROR: test_minilib_contains_paver (tests_integration.test_minilib.TestMinilib)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 30, in setUp
    self.prepare_virtualenv()
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 37, in prepare_virtualenv
    self.bootstrap_virtualenv()
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 57, in bootstrap_virtualenv
    paver.virtual._create_bootstrap(script_name="bootstrap.py",
  File "/build/python-paver/src/paver-Paver-1.3.4/paver/virtual.py", line 91, in _create_bootstrap
    bootstrap_contents = venv.create_bootstrap_script(extra_text)
AttributeError: module 'virtualenv' has no attribute 'create_bootstrap_script'

======================================================================
ERROR: test_minilib_bundles_extra_modules (tests_integration.test_minilib.TestMinilibExtraModules)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/test_minilib.py", line 95, in setUp
    super(TestMinilibExtraModules, self).setUp()
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 30, in setUp
    self.prepare_virtualenv()
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 37, in prepare_virtualenv
    self.bootstrap_virtualenv()
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 57, in bootstrap_virtualenv
    paver.virtual._create_bootstrap(script_name="bootstrap.py",
  File "/build/python-paver/src/paver-Paver-1.3.4/paver/virtual.py", line 91, in _create_bootstrap
    bootstrap_contents = venv.create_bootstrap_script(extra_text)
AttributeError: module 'virtualenv' has no attribute 'create_bootstrap_script'

======================================================================
ERROR: test_minilib_bundles_extra_packages (tests_integration.test_minilib.TestMinilibExtraPackages)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/test_minilib.py", line 61, in setUp
    super(TestMinilibExtraPackages, self).setUp()
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 30, in setUp
    self.prepare_virtualenv()
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 37, in prepare_virtualenv
    self.bootstrap_virtualenv()
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 57, in bootstrap_virtualenv
    paver.virtual._create_bootstrap(script_name="bootstrap.py",
  File "/build/python-paver/src/paver-Paver-1.3.4/paver/virtual.py", line 91, in _create_bootstrap
    bootstrap_contents = venv.create_bootstrap_script(extra_text)
AttributeError: module 'virtualenv' has no attribute 'create_bootstrap_script'

======================================================================
ERROR: test_running_task_in_specified_virtualenv (tests_integration.test_virtualenv.TestVirtualenvTaskSpecification)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 30, in setUp
    self.prepare_virtualenv()
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 37, in prepare_virtualenv
    self.bootstrap_virtualenv()
  File "/build/python-paver/src/paver-Paver-1.3.4/tests_integration/venvtest.py", line 57, in bootstrap_virtualenv
    paver.virtual._create_bootstrap(script_name="bootstrap.py",
  File "/build/python-paver/src/paver-Paver-1.3.4/paver/virtual.py", line 91, in _create_bootstrap
    bootstrap_contents = venv.create_bootstrap_script(extra_text)
AttributeError: module 'virtualenv' has no attribute 'create_bootstrap_script'

----------------------------------------------------------------------
Ran 114 tests in 0.257s

FAILED (errors=5)
```

**Comment by Almad** [comment]
@felixonmars I unfortunately still haven't got time to look into it deeply—do you know if v20 offers same functionality? Since v20 is a rewrite, it looks like more complicated change than a function call...?

**Comment by jxanders** [comment]
On windows it also points to the old activation script:
`FileNotFoundError: [Errno 2] No such file or directory: 'env\\Scripts\\activate_this.py'`

**Comment by Almad** [comment]
Oh. Thanks for the report, I actually have windows now and more time starting next month, I'll try to look into it.
