### ISSUE TITLE
Installation fails with --root option

### ISSUE THREAD

**Issue by Arfrever** [paver/paver#71]
This is a regression in Paver 1.1.0.
Installation of Paver 1.0.5 works correctly with --root option.
Paver 1.1.0 seems to incorrectly use distutils. 
Using of --root option is essential for packagers of Python modules.

```
$ python2.7 setup.py install --root=/tmp/root
Checking .pth file support in /tmp/root/usr/lib64/python2.7/site-packages/
/usr/bin/python2.7 -E -c pass
TEST FAILED: /tmp/root/usr/lib64/python2.7/site-packages/ does NOT support .pth files
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    paver.tasks.main()
  File "/tmp/Paver-1.1.0/paver/tasks.py", line 816, in main
    _launch_pavement(args)
  File "/tmp/Paver-1.1.0/paver/tasks.py", line 797, in _launch_pavement
    _process_commands(args, auto_pending=auto_pending)
  File "/tmp/Paver-1.1.0/paver/tasks.py", line 753, in _process_commands
    task()
  File "/tmp/Paver-1.1.0/paver/setuputils.py", line 173, in __call__
    _extra_command_dispatch[str(self.command_class)](self.distribution, self.command_name)
  File "/tmp/Paver-1.1.0/paver/setuputils.py", line 54, in _dispatch_setuptools_install
    cmd.do_egg_install()
  File "/usr/lib64/python2.7/site-packages/setuptools/command/install.py", line 87, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
  File "/usr/lib64/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 296, in finalize_options
    if not self.editable: self.check_site_dir()
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 432, in check_site_dir
    raise DistutilsError(self.no_default_version_msg())
distutils.errors.DistutilsError: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /tmp/root/usr/lib64/python2.7/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  http://packages.python.org/distribute/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.
```

**Comment by minusdavid** [comment]
Hasn't distribution been merged into setuptools?

I'm having this exact problem with a different project and pulling my hair out trying to solve it...

**Comment by minusdavid** [comment]
This actually worked for me: 
https://github.com/automl/random_forest_run/commit/f975f947979cd1bc46eca30833f8267c2f71514c

Although I don't know why...
